name: CI (lint + smoke run)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (fast)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pandas numpy matplotlib statsmodels pulp openpyxl

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 src --max-line-length=100

      - name: Smoke-run scripts
        env:
          MPLBACKEND: Agg
        run: |
          python src/run_forecast.py
          python src/run_optimisation.py
